INSERT INTO users VALUES
('user1', md5('user1'),'user1@gmail.com',NOW(),NOW(),'user'),
('user2', md5('user2'),'user2@gmail.com',NOW(),NOW(),'user'),
('user3', md5('user3'),'user3@gmail.com',NOW(),NOW(),'user'),
('user4', md5('user4'),'user4@gmail.com',NOW(),NOW(),'user'),
('user5', md5('user5'),'user5@gmail.com',NOW(),NOW(),'user'),
('user6', md5('user6'),'user6@gmail.com',NOW(),NOW(),'user'),
('user7', md5('user7'),'user7@gmail.com',NOW(),NOW(),'user'),
('user8', md5('user8'),'user8@gmail.com',NOW(),NOW(),'user'),
('user9', md5('user9'),'user9@gmail.com',NOW(),NOW(),'user'),
('user10', md5('user10'),'user10@gmail.com',NOW(),NOW(),'user'),
('user11', md5('user11'),'user11@gmail.com',NOW(),NOW(),'user'),
('user12', md5('user12'),'user12@gmail.com',NOW(),NOW(),'user'),
('user13', md5('user13'),'user13@gmail.com',NOW(),NOW(),'user'),
('user14', md5('user14'),'user14@gmail.com',NOW(),NOW(),'user'),
('user15', md5('user15'),'user15@gmail.com',NOW(),NOW(),'user'),
('user16', md5('user16'),'user16@gmail.com',NOW(),NOW(),'user'),
('user17', md5('user17'),'user17@gmail.com',NOW(),NOW(),'user'),
('user18', md5('user18'),'user18@gmail.com',NOW(),NOW(),'user'),
('user19', md5('user19'),'user19@gmail.com',NOW(),NOW(),'user'),
('user20', md5('user20'),'user20@gmail.com',NOW(),NOW(),'user'),
('admin1',md5('admin1'),'admin1@gmail.com',NOW(),NOW(),'admin'),
('админ',md5('админ'),'админ@gmail.com',NOW(),NOW(),'admin'),
('юзер',md5('юзер'),'юзер@gmail.com',NOW(),NOW(),'user')
;